# Generated by Django 4.1.5 on 2026-07-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fact_app', '0002_alter_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_date_time', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='draft', max_length=10)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.customer')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Article',
                'verbose_name_plural': 'Presupuesto Articles',
            },
        ),
    ]
